name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build, lint, and Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Build, Test, and Lint
        uses: remedyred/check-action@v1.0.0
